version: "3.2"
services:
  coord:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: coord
    environment:
      - cluster.name=coord_cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - node.name=coord
    cap_add:
      - IPC_LOCK
    volumes:
      - ./coord_data:/usr/share/elasticsearch/data
      - ./config/coord_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    links:
      - cluster1_data01
      - cluster2_data01

  cluster1_data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: cluster1_data01
    environment:
      - cluster.name=cluster1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - node.name=cluster1_data01
    cap_add:
      - IPC_LOCK
    volumes:
      - ./cluster1_data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
     

  cluster2_data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: cluster2_data01
    environment:
      - cluster.name=cluster2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - node.name=cluster2_data01
    cap_add:
      - IPC_LOCK
    volumes:
      - ./cluster1_data02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    

  kibana1:
    build: kibana
    environment:
      ELASTICSEARCH_URL: http://coord:9200
      SERVER_HOST: kibana1
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - coord
    ports:
      - 5601:5601




