version: '2'
services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch01
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - node.name=node1

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9201:9200

  elasticsearch02:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch02
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "discovery.zen.ping.unicast.hosts=elasticsearch01"
      - http.host=0.0.0.0
      - node.name=node2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    ports:
      - 9202:9200


  kibana1:
    image: docker.elastic.co/kibana/kibana:5.3.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
      SERVER_HOST: kibana1
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch01
    ports:
      - 5601:5601

# volumes:
#   esdata1:
#     driver: local


